name: Update README with Solved Problems

on:
  push:
    paths:
      - "CODING_PRACTICE/**"   # run only when files inside CODING_PRACTICE/ change
  workflow_dispatch:           # allow manual trigger

permissions:
  contents: write   # allow the action to commit changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run update script
        run: python python.py   # make sure python.py is at repo root

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update solved problems list" || echo "No changes"
          git push
